### ISSUE TITLE
spaceship A required agreement is missing or has expired

### ISSUE THREAD

**Issue by aturan23** [rogerluan/app-store-connect-notifier#169]
Hi! Tried:
```
sudo bundle install
npm install
```
All is correct. But  on starting the app with `npm start`:
```
Fetching latest app status...
There was a problem fetching the status of the app!
/Users/aturan23/apps/app-store-connect-notifier/.vendor/ruby/3.0.0/gems/fastlane-2.199.0/spaceship/lib/spaceship/connect_api/api_client.rb:226:in `handle_error': A required agreement is missing or has expired. - This request requires an in-effect agreement that has not been signed or has expired. (Spaceship::ProgramLicenseAgreementUpdated)
	from /Users/aturan23/apps/app-store-connect-notifier/.vendor/ruby/3.0.0/gems/fastlane-2.199.0/spaceship/lib/spaceship/client.rb:922:in `block in send_request'
	from /Users/aturan23/apps/app-store-connect-notifier/.vendor/ruby/3.0.0/gems/fastlane-2.199.0/spaceship/lib/spaceship/client.rb:677:in `with_retry'
	from /Users/aturan23/apps/app-store-connect-notifier/.vendor/ruby/3.0.0/gems/fastlane-2.199.0/spaceship/lib/spaceship/client.rb:918:in `send_request'
	from /Users/aturan23/apps/app-store-connect-notifier/.vendor/ruby/3.0.0/gems/fastlane-2.199.0/spaceship/lib/spaceship/client.rb:762:in `request'
	from /Users/aturan23/apps/app-store-connect-notifier/.vendor/ruby/3.0.0/gems/fastlane-2.199.0/spaceship/lib/spaceship/connect_api/api_client.rb:106:in `block in get'
	from /Users/aturan23/apps/app-store-connect-notifier/.vendor/ruby/3.0.0/gems/fastlane-2.199.0/spaceship/lib/spaceship/connect_api/api_client.rb:162:in `with_asc_retry'
	from /Users/aturan23/apps/app-store-connect-notifier/.vendor/ruby/3.0.0/gems/fastlane-2.199.0/spaceship/lib/spaceship/connect_api/api_client.rb:105:in `get'
	from /Users/aturan23/apps/app-store-connect-notifier/.vendor/ruby/3.0.0/gems/fastlane-2.199.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:22:in `get_apps'
	from /Users/aturan23/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/forwardable.rb:238:in `get_apps'
	from /Users/aturan23/apps/app-store-connect-notifier/.vendor/ruby/3.0.0/gems/fastlane-2.199.0/spaceship/lib/spaceship/connect_api/models/app.rb:74:in `all'
	from /Users/aturan23/apps/app-store-connect-notifier/.vendor/ruby/3.0.0/gems/fastlane-2.199.0/spaceship/lib/spaceship/connect_api/models/app.rb:80:in `find'
	from src/fetch_app_status.rb:91:in `block in get_app_version_from'
	from src/fetch_app_status.rb:90:in `each'
	from src/fetch_app_status.rb:90:in `get_app_version_from'
	from src/fetch_app_status.rb:119:in `block in <main>'
	from src/fetch_app_status.rb:117:in `each'
	from src/fetch_app_status.rb:117:in `<main>'
```

Week ago all worked fine. But now not

**Comment by aturan23** [comment]
It was account holder should agree with new agreements of appstore taxes
